# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 07:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Pentagram', '0006_auto_20160719_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='likes',
            name='like',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 19, 7, 22, 27, 539322, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
